import {createRpc, collect, evaluate, TRANSFER} from '../src/verify.js';
import {writeFileSync, mkdirSync} from 'node:fs';
const directory = process.env.FINALITY_RECEIPTS;
if(!directory) throw new Error('Set FINALITY_RECEIPTS to a private output directory.');
mkdirSync(directory,{recursive:true});
const rpc = createRpc('https://ethereum-rpc.publicnode.com');
const token='0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48';
const finalized = await rpc('eth_getBlockByNumber',['finalized',false]);
const logs = await rpc('eth_getLogs',[{address:token,topics:[TRANSFER],fromBlock:'0x'+(BigInt(finalized.number)-10n).toString(16),toBlock:finalized.number}]);
const first = logs.find(l=>l.topics.length===3 && /^0x[0-9a-f]{64}$/i.test(l.data) && BigInt(l.data)>0n);
if(!first)throw new Error('No ERC20 holdout found in the bounded 11-block window.');
const request={chainId:'1',transactionHash:first.transactionHash,token,recipient:'0x'+first.topics[2].slice(-40),amount:BigInt(first.data).toString()};
const observation = await collect(request,rpc);
const report=evaluate(request,observation);
const mutated=evaluate({...request,amount:(BigInt(request.amount)+1n).toString()},observation);
const passed=report.status==='finalized'&&mutated.status==='mismatch';
writeFileSync(directory+'/live-holdout.json',JSON.stringify({request,observation,report,mutated,passed,source:'https://ethereum-rpc.publicnode.com'},null,2));
console.log(JSON.stringify({passed,status:report.status,mutation:mutated.status,block:report.block?.number,transaction:request.transactionHash}));
if(!passed)process.exitCode=1;
